### ISSUE TITLE
Combine results

### ISSUE THREAD

**Issue by jacques-ivy** [acple/ParsecSharp#1]
As there is not really any documentation, would anyone please kindly tell me how to combine two Parsers in a way that the result will be a list of them? So e.g. I have a `Parser<char,char>` and a different `Parser<char,char>` and want a `Parser<char, IEnumerable<char>>`.

**Comment by acple** [comment]
Sorry for your inconvenience, as there is no well-constructed documentations.

If you want to combine two or more parsers that have a same type, you can use
`Parser<TToken, IEnumerable<T>> Sequence<TToken, T>(params Parser<TToken, T>[] parsers)`
 method. like this
```csharp
var combined = Sequence(parser1, parser2) // Parser<char, IEnumerable<char>>
```

And also, if you actually want to combine parsers that have different types, it is better choice to use `LINQ query notation`.
```csharp
var combined =
    from x in parser1
    from y in parser2
    select new MyRecord(x, y); // any classes as you like
```

**Comment by jacques-ivy** [comment]
Ok thanks ^^
